### ISSUE TITLE
Add a possibility to configure HttpClient client

### ISSUE THREAD

**Issue by msimonides** [mr3y-the-programmer/PodcastIndex-SDK#10]
## The problem I'm trying to solve:
Add custom certificate root to support Let's Encrypt certificates on older Android versions. My app is Android-only.

The simplest approach for my non-multiplatform case is to provide an instance of `OkHttpClient` that is already configured and used throughout the rest of my code.  
An alternative would be to configure the ktor `HttpClient` for PodcastIndex-SDK in an identical way.

Currently I don't think either is possible.

### 1. Allow configuration of only the HttpClientConfig.

Extend `PodcastIndexClientConfig` with:
```
public var customHttpClientEngineConfig: HttpClientConfig<*>.() -> Unit = {}
```
then in application code:
```
PodcastIndexClient(
    podcastindexKey,
    podcastindexSecret,
    uaString
) {
    customHttpClientEngineConfig = {
        engine {
            (this as OkHttpConfig).preconfigured = okHttpClient
        }
    }
}
```
This provides just enough flexibility, although we lose type safety on the http engine type so I need to cast to `OkHttpConfig`.

### 2. Add a custom factory for the whole `HttpClient`:

Extend `PodcastIndexClientConfig` with:
```
public var httpClientFactory: (HttpClientConfig<*>.() -> Unit) -> HttpClient = { httpClientConfig ->
    HttpClient(defaultHttpClientEngineFactory()) {
        httpClientConfig()
    }
}
```
then the application code becomes:
```
PodcastIndexClient(
    podcastindexKey,
    podcastindexSecret,
    uaString
) {
    httpClientFactory = { configBlock ->
        val engine = OkHttp.create {
            preconfigured = okHttpClient
        }
        HttpClient(engine, configBlock)
    }
}
```
Notice how the application needs to pass the `configBlock` to configure everything properly. That's a bit of a trap to the API user, it's easy to miss.  
This approach provides much more flexibility but it's not always a good thing, it might constrain some future modifications to the library.

## To the point
I can provide a PR but I don't know what your plans for the API are and what's the better way of implementing this (also, I have little experience with multiplatform code).  
My gut feeling is to go with 1. What would you suggest?

**Comment by mr3y-the-programmer** [comment]
Hi @msimonides, Thank you for the detailed proposal.

Allowing users to configure the HTTP client directly from their code is indeed part of the API's roadmap. In fact, when I was prototyping the API the `PodcastIndexClient` fun accepted an additional lambda to configure the underlying client but later on I decided to remove this to make the API surface as minimal as possible and the plan was to gradually start adding new parameter options to it in later versions. 

Speaking of which approach to follow, I tend to go with Approach 1 same as you but with some modifications to make the API idiomatic and keep ABI breaking changes minimal.

I really appreciate your effort, and I'd be happy to review your PR and make any additional adjustments (if any). So, go ahead and don't worry the code of the library is very small so you should have no issues understanding or modifying it.

**Comment by mr3y-the-programmer** [comment]
0.4.0 release is now out with support for this feature 🎉
