### ISSUE TITLE
How to implement it KMP project

### ISSUE THREAD

**Issue by tawhidmonowar** [mr3y-the-programmer/PodcastIndex-SDK#9]
Hi, thank you for this library. I'm trying to implement it on my my KMP project but I don't understand how to do that, is there any simple tutorial? I'm new in KMP

**Comment by tawhidmonowar** [comment]
Where to add BuildConfig.API_KEY, BuildConfig.API_SECRET

**Comment by mr3y-the-programmer** [comment]
Hi, the README has a [Download](https://github.com/mr3y-the-programmer/PodcastIndex-SDK?tab=readme-ov-file#download) section to help you add this library to your Kotlin Multiplatform project (just add the dependency under commonMain dependencies, and make sure you have `mavenCentral()` repository in your repositories declaration).

BuildConfig isn't part of this library, it is just a convenient way to access values that change between builds or sensitive info (API_KEY, API_SECRET in this case) that shouldn't be part of your git repository, you can read more about Build Config [here](https://developer.android.com/build/gradle-tips#share-custom-fields-and-resource-values-with-your-app-code) and there are some plugins [1](https://github.com/gmazzo/gradle-buildconfig-plugin) [2](https://github.com/yshrsmz/BuildKonfig) in KMP that can generate BuildConfig class

You're free to use whatever mechanism to securely access your API_KEY & API_SECRET or even include them directly in code(if that what you want), as far as this library is concerned it just needs valid credentials, how to secure & provide those credentials is your responsibility and beyond the scope of this project.

If you want a full example that you can directly run and follow, here it is: https://github.com/mr3y-the-programmer/PodcastIndexSDKSample

clone the repo, and add your credentials obtained from PodcantIndex org to your `local.properties` file like this:
```
API_KEY=your API key
API_SECRET=your API secret
```

**Comment by tawhidmonowar** [comment]
Thank you.
